version: "3.8"
services:
  message-broker:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  localstack:
    image: localstack/localstack
    expose:
      - "4566"
    restart: always
  discovery-server:
    build: discovery-server
    ports:
      - "8761:8761"
    restart: always
  resource-service:
    build: resource-service
    ports:
      - "7000:8080"
    depends_on:
      - message-broker
      - resource-service-db
      - discovery-server
    restart: always
  song-service:
    build: song-service
    expose:
      - "8080"
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - discovery-server
    restart: always
  resource-service-db:
    image: postgres
    expose:
      - 5432
    volumes:
      - resource-service-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=resources
    restart: always
  resource-processor:
    build: resource-processor
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - message-broker
volumes:
  resource-service-db:
