server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
spring:
  application:
    name: resource-service
  datasource:
    url: jdbc:postgresql://resource-service-db:5432/resources
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
clients:
  s3:
    url: http://localstack:4566
    bucket: some-bucket
    access_key: key_access
    secret_key: key_id
  song-service: SONG-SERVICE
